#!/bin/bash
if [ "$1" = "" ]; then
	echo "you need to pass the project name as an argument!"
	exit 1
fi
# crea la cartella del progetto
echo 'creating the project folder...'
mkdir $1
echo '	done'
# si sposta nella cartella creata
cd $1
# crea le sottocartelle
#	src
#	include
echo 'creating the src and include directories...'
mkdir src include
echo '	done'
# crea il file main.cpp
echo 'creating the Main.cpp file...'
user=$(whoami)
dateOfCreation=$(date)
comm="// ${dateOfCreation}\n// ${user}\n\n#include<iostream>\n\nusing namespace std;\n\nint main() {\n\n}"
echo -e ${comm} > ./src/Main.cpp
echo '	done'
echo 'creating the cmake file...'
printf "cmake_minimum_required(VERSION 3.10)\nproject(%s)\nfile(GLOB SOURCES ./src/*)\nadd_executable(%s %s)\ntarget_include_directories(%s PUBLIC %s)" "${1}" "${1}" "\${SOURCES}" "${1}" '"./include"'> CMakeLists.txt
echo '	done'
echo 'finished creation of the project.'
